### ISSUE TITLE
Show online presence of staff members

### ISSUE THREAD

**Issue by knrafto** [Cal-CS-61A-Staff/oh-queue#113]
especially for online OH

**Comment by itsnshaw** [comment]
Can this issue be closed?

**Comment by jathak** [comment]
I think we left it open because the [online queue](https://online.cs61a.org) is based off of a separate branch that's very old (prior to #119). If the online queue is no longer used, I think it's fine to close this. Otherwise, should merge the presence feature into the online branch first

**Comment by itsnshaw** [comment]
We're currently not using the online queue; however I'm not sure if John or Dan might decide to use it in the future. Does merging just involve redeployment?

**Comment by jathak** [comment]
[This branch](https://github.com/Cal-CS-61A-Staff/oh-queue/tree/online_support) needs to be updated with the new code and then that branch should be deployed to the online instance

**Comment by Penguinlay** [comment]
I am working on this.

**Comment by pbitutsky** [comment]
Can you please clarify. Do you mean list the names of staff members who are online or just the number of staff members?
