### ISSUE TITLE
Multi-select and edit tickets

### ISSUE THREAD

**Issue by epai** [Cal-CS-61A-Staff/oh-queue#134]
Another enhancement (possibly more difficult) is to allow staff to multi-select different tickets to resolve/delete etc.  Right now, you can only group and help/delete all, which doesn't allow for fine-grain editing.

**Comment by ja5087** [comment]
Hi, I'd like to take this on

**Comment by pbitutsky** [comment]
This should not be a feature. We don't want anyone to accidentally delete 100 tickets from the Queue with no way of getting them back.
