### ISSUE TITLE
Allow students to put their ticket on hold

### ISSUE THREAD

**Issue by jathak** [Cal-CS-61A-Staff/oh-queue#140]
It would be nice for students to put a temporary hold on their ticket if they need to go to the bathroom (or something similar).

**Comment by wvshelu** [comment]
Hello @jathak! @Bridgetc9 and I will try working on this. To prevent people from taking advantage by putting themselves on the queue while they are in class, we will allow students to put their ticket on hold for a maximum of 30 minutes before they must put themselves back on queue.

**Comment by rahularya50** [comment]
Is this closed by #196? Staff members can put students on hold, but students cannot put themselves on hold. This has the same basic functionality but prevents students from using this feature to camp out at the top of the OH queue, since a staff member must put them on hold manually.
