### ISSUE TITLE
Add ability for TAs to change announcements

### ISSUE THREAD

**Issue by pbitutsky** [Cal-CS-61A-Staff/oh-queue#170]
This is what the CS 70 OH Queue looks like. TA's should have the ability to edit the text and add/remove bullet points. 

<img width="1552" alt="Screen Shot 2019-04-08 at 10 43 31 PM" src="https://user-images.githubusercontent.com/6360587/55775930-d4c35c80-5a4f-11e9-8eeb-8d2fa8b35107.png">

**Comment by pbitutsky** [comment]
@chrononyan would you be interested in working on this? I think this could go into the admin panel.

**Comment by chrononyan** [comment]
@pbitutsky I can tackle this locally, but I want to avoid PR-ing changes to the admin panel until the admin panel lands in #169 (potential merge conflicts)

**Comment by kristyelee** [comment]
I can work on this.
