### ISSUE TITLE
Feature Request: Juggling

### ISSUE THREAD

**Issue by pbitutsky** [Cal-CS-61A-Staff/oh-queue#174]
It would be really useful if we had a feature where a staff member could spend 5 minutes helping a student, put the student on hold (Juggle Mode?), then go help another student, and then come back to the original student.

**Comment by rahularya50** [comment]
People _explicitly_ didn't want it when I asked in staff meeting

**Comment by nicholasngai** [comment]
Then tell them not to use it when it’s implemented. :/
