### ISSUE TITLE
Update "Your Appointments" Panel card design

### ISSUE THREAD

**Issue by vivrekar** [Cal-CS-61A-Staff/oh-queue#203]
Can we make the the time appear in a new line below the date so it is easier for a viewer to scan the panels and see the time?

Current:
<img width="315" alt="Screen Shot 2020-03-10 at 7 14 43 PM" src="https://user-images.githubusercontent.com/25167018/76375577-68a64400-6303-11ea-9385-b850bb3baa4d.png">

Request:
<img width="318" alt="your appointments time h4" src="https://user-images.githubusercontent.com/25167018/76375536-4f9d9300-6303-11ea-9940-d1dee1fb303f.png">

This way the user doesn't have to read and parse the entire h3 heading of the date and time to get the important information about time.

**Comment by rahularya50** [comment]
Implemented in 5e6d1f.
