### ISSUE TITLE
Consistency in viewing names of students

### ISSUE THREAD

**Issue by vivrekar** [Cal-CS-61A-Staff/oh-queue#204]
On a the page for viewing a particular appointment, it says that the TA must start an appointment to view the student's name.
<img width="1002" alt="Screen Shot 2020-03-10 at 7 17 33 PM" src="https://user-images.githubusercontent.com/25167018/76375806-ea966d00-6303-11ea-8214-da49f77e4e29.png">

However, you can view the students' names in the "Regular" view on the https://oh.cs61a.org/appointments page.
<img width="1007" alt="Screen Shot 2020-03-10 at 7 17 44 PM" src="https://user-images.githubusercontent.com/25167018/76375840-feda6a00-6303-11ea-8dbe-46cfe62cd17c.png">

I think it would be good to be consistent across these two screens and either allow TAs to see student names from both views, or disallow TAs to see student names from both views.

**Comment by rahularya50** [comment]
Closed with #c1752c1
