### ISSUE TITLE
Not show Appointment Limits alert to staff?

### ISSUE THREAD

**Issue by vivrekar** [Cal-CS-61A-Staff/oh-queue#205]
<img width="955" alt="Screen Shot 2020-03-15 at 7 46 14 PM" src="https://user-images.githubusercontent.com/25167018/76719016-bfda5900-66f5-11ea-8226-474749eaeff4.png">
Should staff see this alert or is it only for students?

**Comment by rahularya50** [comment]
Staff as well, just like how staff see the welcome message + OH queue timer
