### ISSUE TITLE
Live Chat Buggy

### ISSUE THREAD

**Issue by itsnshaw** [Cal-CS-61A-Staff/oh-queue#215]
"Hm the live chat feature appears to be kind of buggy. After a couple of messages, the page freezes (has happened several times). Also for context, a student wanted to live chat instead of zoom, so we tried a live chat session. Didn't work very well."

**Comment by rahularya50** [comment]
Live chat is not meant to be used instead of zoom! It's only meant to help resolve technical difficulties. Can you reproduce the freezing bug?

**Comment by jemmy-z** [comment]
I could reproduce the bug within one session. The student also noticed the chat was "laggy". The student didn't have Zoom ready to go, so we couldn't use it. I guess we can emphasize requirements like setting up Zoom before signing up for office hours.

**Comment by rahularya50** [comment]
Fixed ages ago
