### ISSUE TITLE
Ability for TAs to close the queue to new signups

### ISSUE THREAD

**Issue by jathak** [Cal-CS-61A-Staff/oh-queue#60]
A TA or tutor (but not a lab assistant) should be able to close the queue to new signups so that they can formalize only helping students that added before office hours officially ended.

This could either be a toggle or perhaps be on some sort of automatic timer. It should also be on a room-by-room basis so that, for instance, the last TA to leave Morgan could lock their queue without causing any issues for the OH starting in Cory. This likely means that this would want to wait for #29.

**Comment by itsnshaw** [comment]
Re-adding priority label since it seems to be an issue again.
