### ISSUE TITLE
Timer for staff to see time spent on ticket

### ISSUE THREAD

**Issue by Sumukh** [Cal-CS-61A-Staff/oh-queue#76]
![image](https://cloud.githubusercontent.com/assets/882381/18900893/d48b92a0-84fa-11e6-9231-b45f0bbb0a82.png)

It'd be useful to have an at a glance view of how many minutes have been spent on a ticket once it has been assigned (this would be for staff only - having it shown to students might be troublesome). 

The table could look like:

```
Time Spent  | Status 
1 minute    | Assigned to .... 
 -          | Queued
```

(including seconds might be too much - we don't want staff to race)

**Comment by stella-lu** [comment]
Will try to work on this!
